---
- name: Ensure MySQL server is uninstalled
  action: apt pkg={{ item }} state=absent
  with_items:
          - mysql-server-core-5.5
          - mysql-client 
          - mysql-client-5.5
          - mysql-client-core-5.5

- name: Install percona database server
  action: apt pkg={{ item }} state=latest
  with_items:
          - "{{ percona_package }}"
          - percona-toolkit
          - percona-xtrabackup
          - python-mysqldb
  register: install_result
  notify:
    - restart percona

- name: Write custom server configuration
  template: src=etc_mysql_my.cnf.j2 dest=/etc/mysql/my.cnf owner=root mode=0600
  notify:
    - restart percona

- name: Detect bootstrapping
  set_fact:
    bootstrapping: true
  when: percona_master_node and install_result|changed

- name: Run bootstrap-pxc on this node
  command: /etc/init.d/mysql bootstrap-pxc
  when: bootstrapping

- meta: flush_handlers  # Restart now before attempting to set root password
- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
   - "{{ ansible_hostname }}"
   - 127.0.0.1
   - ::1
   - localhost
  when: ansible_hostname != 'localhost'

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
   - 127.0.0.1
   - ::1
   - localhost
  when: ansible_hostname == 'localhost'

- name: Copy .my.cnf file into the root home folder
  template: src=root-my-cnf.j2 dest=~/.my.cnf owner=root mode=0600

- name: Ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
          - "{{ ansible_hostname }}"
          - localhost

- name: remove test database
  mysql_db: name=test state=absent

